#!/bin/bash

for ((method=0; method<=1; method++))
do
for ((m=100; m<=1000; m+=100))
do
for ((count=-5000; count<=5000; count++))
do
    # Execute the bash code with ../bin/golomb and the current value of count
    output=$(../bin/golomb $count $m $method)
    
    # Compare the output with the expected value
    expected_output=$count
    if [ "$output" != "$expected_output" ]; then
        echo "Test $count failed: Expected $expected_output but got $output"
    fi
done
echo "m=$m done"
done
echo "method=$method done"
done